name: Markdown Lint

on:
  push:
    paths:
      - '**.md'
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Markdown Linter
        uses: DavidAnson/markdownlint-cli2-action@v13
